add openwrt init
mylittletony/SocketMan pull request #4
Opened 2017-02-02 11:22 UTC by AndrewMargarit

2017-02-07 10:46 UTC, simonmorley requested changes

2017-02-07 10:46 UTC, simonmorley commented on examples/openwrt/init.d/socketman.init
> +        generate_mac
Indent please

2017-02-07 10:46 UTC, simonmorley commented on examples/openwrt/init.d/socketman.init
> +        echo "Restarting Socketman"
Capitalize the M

2017-02-07 10:46 UTC, simonmorley commented on examples/openwrt/init.d/socketman.init
> +        echo "Starting Socketman"
Capitalize M

2017-02-07 10:46 UTC, simonmorley commented on examples/openwrt/init.d/socketman.init
> +# Copyright (C) 2015 Cucumber WiFi
Think this is now 17

2017-02-08 17:14 UTC, AndrewMargarit commented
I have a newer version.

2017-02-08 17:14 UTC, closed without merging